# -*- encoding: utf-8 -*-
$:.unshift(File.join(File.dirname(__FILE__), "..", "lib"))
require 'rspec'
require 'smartgen'
require 'smartgen_erb/pre_processor'

describe ErbPreProcessor do

  it "should render textile code generated by erb" do
    body = """
    <% 1.upto(6) do |i|
         if (i % 2) == 1
    %>
    * <%= i %>
    <%   end
       end
    %>
    """
    subject.process(body).should == "\n    \n    * 1\n    \n    * 3\n    \n    * 5\n    \n    "
  end

  it "should render textile code generated by erb accessing metadata" do
    body = "*<%= metadata.user.name %>* <%= metadata.user.surname %>"
    subject.process(body, {:user => {:name => 'John', :surname => 'Nesh'} }).should == "*John* Nesh"
  end

end
